### ISSUE TITLE
Error while installing jupyter-ros2

### ISSUE THREAD

**Issue by hsd-dev** [zmk5/jupyter-ros2#10]
The command 
```
$ jupyter labextension install jupyter-ros2
```
gives an error
```
An error occured.
ValueError: "/home/user/notebook/jupyter-ros2" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-c411be55.log
```
So I tried the development installation
```
~$ git clone https://github.com/zmk5/jupyter-ros2.git
~$ cd jupyter-ros2
~$ python3 -m pip install -e .
```
The error log is
```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/user/notebook/jupyter-ros2/setup.py'"'"'; __file__='"'"'/home/user/notebook/jupyter-ros2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/user/notebook/jupyter-ros2/
    Complete output (155 lines):
    setup.py entered
    $PATH=/opt/ros/foxy/bin:/home/hsd/projects/rosin/env3/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    running egg_info
    running jsdeps
    7.11.2
    7.11.2
    Installing build dependencies with npm.  This may take a while...
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: 'rclnodejs@0.18.2',
    npm WARN EBADENGINE   required: { node: '>= 10.23.1 <13.0.0' },
    npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
    npm WARN EBADENGINE }
    npm ERR! code 1
    npm ERR! git dep preparation failed
    npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/user/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
    npm ERR! > rclnodejs@0.18.2 install
    npm ERR! > node-gyp rebuild
    npm ERR!
    npm ERR! make: Entering directory '/home/user/.npm/_cacache/tmp/git-clone-c1189b66/build'
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/addon.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/executor.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/handle_manager.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/rcl_action_bindings.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/rcl_bindings.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/rcl_handle.o
    npm ERR!   CXX(target) Release/obj.target/rclnodejs/src/rcl_lifecycle_bindings.o
    npm ERR! make: Leaving directory '/home/user/.npm/_cacache/tmp/git-clone-c1189b66/build'
    npm ERR! npm WARN using --force Recommended protections disabled.
    npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm ERR! npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
    npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.2
    npm ERR! gyp info using node@16.1.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
    npm ERR! (node:87378) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
    npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/user/.npm/_cacache/tmp/git-clone-c1189b66/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/user/.cache/node-gyp/16.1.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/16.1.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/16.1.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/user/.npm/_cacache/tmp/git-clone-c1189b66',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! ../src/rcl_bindings.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE rclnodejs::CreateArrayBufferFromAddress(Nan::NAN_METHOD_ARGS_TYPE)’:
    npm ERR! ../src/rcl_bindings.cpp:1322:70: warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
    npm ERR!  1322 |                            v8::ArrayBufferCreationMode::kInternalized);
    npm ERR!       |                                                                      ^
    npm ERR! In file included from /home/user/.cache/node-gyp/16.1.0/include/node/node.h:63,
    npm ERR!                  from ../node_modules/nan/nan.h:56,
    npm ERR!                  from ../src/rcl_bindings.hpp:18,
    npm ERR!                  from ../src/rcl_bindings.cpp:15:
    npm ERR! /home/user/.cache/node-gyp/16.1.0/include/node/v8.h:5476:29: note: declared here
    npm ERR!  5476 |   static Local<ArrayBuffer> New(
    npm ERR!       |                             ^~~
    npm ERR! ../src/rcl_bindings.cpp:1322:70: warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
    npm ERR!  1322 |                            v8::ArrayBufferCreationMode::kInternalized);
    npm ERR!       |                                                                      ^
    npm ERR! In file included from /home/user/.cache/node-gyp/16.1.0/include/node/node.h:63,
    npm ERR!                  from ../node_modules/nan/nan.h:56,
    npm ERR!                  from ../src/rcl_bindings.hpp:18,
    npm ERR!                  from ../src/rcl_bindings.cpp:15:
    npm ERR! /home/user/.cache/node-gyp/16.1.0/include/node/v8.h:5476:29: note: declared here
    npm ERR!  5476 |   static Local<ArrayBuffer> New(
    npm ERR!       |                             ^~~
    npm ERR! ../src/rcl_lifecycle_bindings.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE rclnodejs::CreateLifecycleStateMachine(Nan::NAN_METHOD_ARGS_TYPE)’:
    npm ERR! ../src/rcl_lifecycle_bindings.cpp:76:3: error: ‘rcl_lifecycle_state_machine_options_t’ was not declared in this scope; did you mean ‘rcl_lifecycle_state_machine_init’?
    npm ERR!    76 |   rcl_lifecycle_state_machine_options_t options =
    npm ERR!       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    npm ERR!       |   rcl_lifecycle_state_machine_init
    npm ERR! In file included from ../src/rcl_lifecycle_bindings.cpp:29:
    npm ERR! ../src/rcl_lifecycle_bindings.cpp:83:33: error: ‘options’ was not declared in this scope; did you mean ‘htons’?
    npm ERR!    83 |                                &options),
    npm ERR!       |                                 ^~~~~~~
    npm ERR! ../src/macros.hpp:22:16: note: in definition of macro ‘CHECK_OP_AND_THROW_ERROR_IF_NOT_TRUE’
    npm ERR!    22 |     if (lhs op rhs) {                                               \
    npm ERR!       |                ^~~
    npm ERR! ../src/rcl_lifecycle_bindings.cpp:79:3: note: in expansion of macro ‘THROW_ERROR_IF_NOT_EQUAL’
    npm ERR!    79 |   THROW_ERROR_IF_NOT_EQUAL(RCL_RET_OK,
    npm ERR!       |   ^~~~~~~~~~~~~~~~~~~~~~~~
    npm ERR! ../src/rcl_lifecycle_bindings.cpp: In lambda function:
    npm ERR! ../src/rcl_lifecycle_bindings.cpp:90:77: error: too few arguments to function ‘rcl_ret_t rcl_lifecycle_state_machine_fini(rcl_lifecycle_state_machine_t*, rcl_node_t*, const rcl_allocator_t*)’
    npm ERR!    90 |         rcl_ret_t ret = rcl_lifecycle_state_machine_fini(state_machine, node);
    npm ERR!       |                                                                             ^
    npm ERR! In file included from ../src/rcl_lifecycle_bindings.cpp:18:
    npm ERR! /opt/ros/foxy/include/rcl_lifecycle/rcl_lifecycle.h:272:1: note: declared here
    npm ERR!   272 | rcl_lifecycle_state_machine_fini(
    npm ERR!       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    npm ERR! make: *** [rclnodejs.target.mk:138: Release/obj.target/rclnodejs/src/rcl_lifecycle_bindings.o] Error 1
    npm ERR! gyp ERR! build error
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    npm ERR! gyp ERR! System Linux 5.8.0-53-generic
    npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /home/user/.npm/_cacache/tmp/git-clone-c1189b66
    npm ERR! gyp ERR! node -v v16.1.0
    npm ERR! gyp ERR! node-gyp -v v7.1.2
    npm ERR! gyp ERR! not ok
    npm ERR! npm ERR! code 1
    npm ERR! npm ERR! path /home/user/.npm/_cacache/tmp/git-clone-c1189b66
    npm ERR! npm ERR! command failed
    npm ERR! npm ERR! command sh -c node-gyp rebuild
    npm ERR!
    npm ERR! npm ERR! A complete log of this run can be found in:
    npm ERR! npm ERR!     /home/user/.npm/_logs/2021-05-18T15_06_14_587Z-debug.log
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/user/.npm/_logs/2021-05-18T15_06_15_455Z-debug.log
    rebuilding js and css failed
    missing files: ['/home/user/notebook/jupyter-ros2/jupyros/static/extension.js', '/home/user/notebook/jupyter-ros2/jupyros/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/notebook/jupyter-ros2/setup.py", line 182, in <module>
        setup(**setup_args)
      File "/home/user/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/notebook/jupyter-ros2/setup.py", line 45, in run
        raise e
      File "/home/user/notebook/jupyter-ros2/setup.py", line 38, in run
        self.distribution.run_command('jsdeps')
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/notebook/jupyter-ros2/setup.py", line 111, in run
        check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hsd-dev** [comment]
Downgraded my node version to v12.22.1 and changed https://github.com/zmk5/jupyter-ros2/blob/f107cbb49065c1c56269403e3ad05bd2feb02b0e/js/package.json#L36 to 
```
    "rclnodejs": "^0.18.2"
```
Now successfully able to install.
